#ifndef __SLOWLOGGER_DEF_H__
#define __SLOWLOGGER_DEF_H__

#define VENUS_REDIS_MSGQ_SLOWLOG_NAME "/tmp/venus-redis-msgq-slowlog"
#define VENUS_REDIS_MSGQ_SLOWLOG_ID 0xe2000001

#define VENUS_REDIS_MSGQ_SLOWLOG_CONTENT_LENGTH 1024

#define VENUS_REDIS_MSGQ_SLOWLOG_ELEM_PID_LENGTH 64 

#define VENUS_REDIS_MSGQ_SLOWLOG_FETCH_USLEEP 100

#define VENUS_SLOWLOG_DB_SQL_LENGTH 256

#endif

